/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerLogout200Response
 */
export interface AuthControllerLogout200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerLogout200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerLogout200Response interface.
 */
export function instanceOfAuthControllerLogout200Response(value: object): value is AuthControllerLogout200Response {
    return true;
}

export function AuthControllerLogout200ResponseFromJSON(json: any): AuthControllerLogout200Response {
    return AuthControllerLogout200ResponseFromJSONTyped(json, false);
}

export function AuthControllerLogout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerLogout200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerLogout200ResponseToJSON(json: any): AuthControllerLogout200Response {
    return AuthControllerLogout200ResponseToJSONTyped(json, false);
}

export function AuthControllerLogout200ResponseToJSONTyped(value?: AuthControllerLogout200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

