/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerRefresh200Response
 */
export interface AuthControllerRefresh200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerRefresh200Response
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the AuthControllerRefresh200Response interface.
 */
export function instanceOfAuthControllerRefresh200Response(value: object): value is AuthControllerRefresh200Response {
    return true;
}

export function AuthControllerRefresh200ResponseFromJSON(json: any): AuthControllerRefresh200Response {
    return AuthControllerRefresh200ResponseFromJSONTyped(json, false);
}

export function AuthControllerRefresh200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerRefresh200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
    };
}

export function AuthControllerRefresh200ResponseToJSON(json: any): AuthControllerRefresh200Response {
    return AuthControllerRefresh200ResponseToJSONTyped(json, false);
}

export function AuthControllerRefresh200ResponseToJSONTyped(value?: AuthControllerRefresh200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
    };
}

