/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthResponseDto
 */
export interface AuthResponseDto {
    /**
     * JWT access token
     * @type {string}
     * @memberof AuthResponseDto
     */
    accessToken: string;
    /**
     * JWT refresh token
     * @type {string}
     * @memberof AuthResponseDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthResponseDto interface.
 */
export function instanceOfAuthResponseDto(
    value: object
): value is AuthResponseDto {
    if (!("accessToken" in value) || value["accessToken"] === undefined)
        return false;
    if (!("refreshToken" in value) || value["refreshToken"] === undefined)
        return false;
    return true;
}

export function AuthResponseDtoFromJSON(json: any): AuthResponseDto {
    return AuthResponseDtoFromJSONTyped(json, false);
}

export function AuthResponseDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AuthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        accessToken: json["access_token"],
        refreshToken: json["refresh_token"],
    };
}

export function AuthResponseDtoToJSON(json: any): AuthResponseDto {
    return AuthResponseDtoToJSONTyped(json, false);
}

export function AuthResponseDtoToJSONTyped(
    value?: AuthResponseDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        access_token: value["accessToken"],
        refresh_token: value["refreshToken"],
    };
}
