/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AvailabilityResponseDto
 */
export interface AvailabilityResponseDto {
    /**
     * Unique identifier for the availability
     * @type {string}
     * @memberof AvailabilityResponseDto
     */
    id: string;
    /**
     * The day of the week (0-6, where 0 is Sunday and 6 is Saturday)
     * @type {number}
     * @memberof AvailabilityResponseDto
     */
    day: number;
    /**
     * Start time of the availability
     * @type {Date}
     * @memberof AvailabilityResponseDto
     */
    startTime: Date;
    /**
     * End time of the availability
     * @type {Date}
     * @memberof AvailabilityResponseDto
     */
    endTime: Date;
}

/**
 * Check if a given object implements the AvailabilityResponseDto interface.
 */
export function instanceOfAvailabilityResponseDto(
    value: object
): value is AvailabilityResponseDto {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("day" in value) || value["day"] === undefined) return false;
    if (!("startTime" in value) || value["startTime"] === undefined)
        return false;
    if (!("endTime" in value) || value["endTime"] === undefined) return false;
    return true;
}

export function AvailabilityResponseDtoFromJSON(
    json: any
): AvailabilityResponseDto {
    return AvailabilityResponseDtoFromJSONTyped(json, false);
}

export function AvailabilityResponseDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AvailabilityResponseDto {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        day: json["day"],
        startTime: new Date(json["startTime"]),
        endTime: new Date(json["endTime"]),
    };
}

export function AvailabilityResponseDtoToJSON(
    json: any
): AvailabilityResponseDto {
    return AvailabilityResponseDtoToJSONTyped(json, false);
}

export function AvailabilityResponseDtoToJSONTyped(
    value?: AvailabilityResponseDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        day: value["day"],
        startTime: value["startTime"].toISOString(),
        endTime: value["endTime"].toISOString(),
    };
}
