/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Availability
 */
export interface Availability {
    /**
     * Unique identifier for the availability
     * @type {string}
     * @memberof Availability
     */
    id: string;
    /**
     * The day of the week (0-6, where 0 is Sunday and 6 is Saturday)
     * @type {number}
     * @memberof Availability
     */
    day: number;
    /**
     * Start time of the availability
     * @type {Date}
     * @memberof Availability
     */
    startTime: Date;
    /**
     * End time of the availability
     * @type {Date}
     * @memberof Availability
     */
    endTime: Date;
    /**
     * Date when the availability was created
     * @type {Date}
     * @memberof Availability
     */
    createdAt: Date;
    /**
     * Date when the availability was last updated
     * @type {Date}
     * @memberof Availability
     */
    updatedAt: Date;
    /**
     * Unique identifier for the user
     * @type {string}
     * @memberof Availability
     */
    userId: string;
}

/**
 * Check if a given object implements the Availability interface.
 */
export function instanceOfAvailability(value: object): value is Availability {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("day" in value) || value["day"] === undefined) return false;
    if (!("startTime" in value) || value["startTime"] === undefined)
        return false;
    if (!("endTime" in value) || value["endTime"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined)
        return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    if (!("userId" in value) || value["userId"] === undefined) return false;
    return true;
}

export function AvailabilityFromJSON(json: any): Availability {
    return AvailabilityFromJSONTyped(json, false);
}

export function AvailabilityFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): Availability {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        day: json["day"],
        startTime: new Date(json["startTime"]),
        endTime: new Date(json["endTime"]),
        createdAt: new Date(json["createdAt"]),
        updatedAt: new Date(json["updatedAt"]),
        userId: json["userId"],
    };
}

export function AvailabilityToJSON(json: any): Availability {
    return AvailabilityToJSONTyped(json, false);
}

export function AvailabilityToJSONTyped(
    value?: Availability | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        day: value["day"],
        startTime: value["startTime"].toISOString(),
        endTime: value["endTime"].toISOString(),
        createdAt: value["createdAt"].toISOString(),
        updatedAt: value["updatedAt"].toISOString(),
        userId: value["userId"],
    };
}
