/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMultipleUserSkillsDto
 */
export interface CreateMultipleUserSkillsDto {
    /**
     * Array of skill IDs to add to user
     * @type {Array<string>}
     * @memberof CreateMultipleUserSkillsDto
     */
    skillIds: Array<string>;
}

/**
 * Check if a given object implements the CreateMultipleUserSkillsDto interface.
 */
export function instanceOfCreateMultipleUserSkillsDto(value: object): value is CreateMultipleUserSkillsDto {
    if (!('skillIds' in value) || value['skillIds'] === undefined) return false;
    return true;
}

export function CreateMultipleUserSkillsDtoFromJSON(json: any): CreateMultipleUserSkillsDto {
    return CreateMultipleUserSkillsDtoFromJSONTyped(json, false);
}

export function CreateMultipleUserSkillsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMultipleUserSkillsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'skillIds': json['skillIds'],
    };
}

export function CreateMultipleUserSkillsDtoToJSON(json: any): CreateMultipleUserSkillsDto {
    return CreateMultipleUserSkillsDtoToJSONTyped(json, false);
}

export function CreateMultipleUserSkillsDtoToJSONTyped(value?: CreateMultipleUserSkillsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skillIds': value['skillIds'],
    };
}

