/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * User email address
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;
    /**
     * User password (minimum 8 characters)
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;
    /**
     * User first name
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName: string;
    /**
     * User last name
     * @type {string}
     * @memberof CreateUserDto
     */
    lastName: string;
    /**
     * User biography
     * @type {string}
     * @memberof CreateUserDto
     */
    biography?: string;
    /**
     * Indicates if the user account is archived
     * @type {boolean}
     * @memberof CreateUserDto
     */
    isArchived: boolean;
    /**
     * User avatar URL
     * @type {string}
     * @memberof CreateUserDto
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the CreateUserDto interface.
 */
export function instanceOfCreateUserDto(value: object): value is CreateUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('isArchived' in value) || value['isArchived'] === undefined) return false;
    return true;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
    return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'isArchived': json['isArchived'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    };
}

export function CreateUserDtoToJSON(json: any): CreateUserDto {
    return CreateUserDtoToJSONTyped(json, false);
}

export function CreateUserDtoToJSONTyped(value?: CreateUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'biography': value['biography'],
        'isArchived': value['isArchived'],
        'avatarUrl': value['avatarUrl'],
    };
}

