/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserSkillDto
 */
export interface CreateUserSkillDto {
    /**
     * ID of the skill to add to user
     * @type {string}
     * @memberof CreateUserSkillDto
     */
    skillId: string;
}

/**
 * Check if a given object implements the CreateUserSkillDto interface.
 */
export function instanceOfCreateUserSkillDto(
    value: object
): value is CreateUserSkillDto {
    if (!("skillId" in value) || value["skillId"] === undefined) return false;
    return true;
}

export function CreateUserSkillDtoFromJSON(json: any): CreateUserSkillDto {
    return CreateUserSkillDtoFromJSONTyped(json, false);
}

export function CreateUserSkillDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateUserSkillDto {
    if (json == null) {
        return json;
    }
    return {
        skillId: json["skillId"],
    };
}

export function CreateUserSkillDtoToJSON(json: any): CreateUserSkillDto {
    return CreateUserSkillDtoToJSONTyped(json, false);
}

export function CreateUserSkillDtoToJSONTyped(
    value?: CreateUserSkillDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        skillId: value["skillId"],
    };
}
