/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * The name of the category
     * @type {string}
     * @memberof CreateCategoryDto
     */
    name: string;
    /**
     * The color of the category in hex code
     * @type {string}
     * @memberof CreateCategoryDto
     */
    color: string;
}

/**
 * Check if a given object implements the CreateCategoryDto interface.
 */
export function instanceOfCreateCategoryDto(
    value: object
): value is CreateCategoryDto {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("color" in value) || value["color"] === undefined) return false;
    return true;
}

export function CreateCategoryDtoFromJSON(json: any): CreateCategoryDto {
    return CreateCategoryDtoFromJSONTyped(json, false);
}

export function CreateCategoryDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        color: json["color"],
    };
}

export function CreateCategoryDtoToJSON(json: any): CreateCategoryDto {
    return CreateCategoryDtoToJSONTyped(json, false);
}

export function CreateCategoryDtoToJSONTyped(
    value?: CreateCategoryDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        color: value["color"],
    };
}
