/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateSkillDto
 */
export interface CreateSkillDto {
    /**
     * Name of the skill
     * @type {string}
     * @memberof CreateSkillDto
     */
    name: string;
    /**
     * Diminutive of the skill
     * @type {string}
     * @memberof CreateSkillDto
     */
    diminutive: string;
    /**
     * Unique identifier for the category
     * @type {string}
     * @memberof CreateSkillDto
     */
    categoryId: string;
}

/**
 * Check if a given object implements the CreateSkillDto interface.
 */
export function instanceOfCreateSkillDto(
    value: object
): value is CreateSkillDto {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("diminutive" in value) || value["diminutive"] === undefined)
        return false;
    if (!("categoryId" in value) || value["categoryId"] === undefined)
        return false;
    return true;
}

export function CreateSkillDtoFromJSON(json: any): CreateSkillDto {
    return CreateSkillDtoFromJSONTyped(json, false);
}

export function CreateSkillDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateSkillDto {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        diminutive: json["diminutive"],
        categoryId: json["categoryId"],
    };
}

export function CreateSkillDtoToJSON(json: any): CreateSkillDto {
    return CreateSkillDtoToJSONTyped(json, false);
}

export function CreateSkillDtoToJSONTyped(
    value?: CreateSkillDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        diminutive: value["diminutive"],
        categoryId: value["categoryId"],
    };
}
