/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateMessageDto
 */
export interface CreateMessageDto {
    /**
     * Content of the message
     * @type {string}
     * @memberof CreateMessageDto
     */
    content: string;
    /**
     * Identifier of the sender of the message
     * @type {string}
     * @memberof CreateMessageDto
     */
    senderId: string;
}

/**
 * Check if a given object implements the CreateMessageDto interface.
 */
export function instanceOfCreateMessageDto(
    value: object
): value is CreateMessageDto {
    if (!("content" in value) || value["content"] === undefined) return false;
    if (!("senderId" in value) || value["senderId"] === undefined) return false;
    return true;
}

export function CreateMessageDtoFromJSON(json: any): CreateMessageDto {
    return CreateMessageDtoFromJSONTyped(json, false);
}

export function CreateMessageDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateMessageDto {
    if (json == null) {
        return json;
    }
    return {
        content: json["content"],
        senderId: json["senderId"],
    };
}

export function CreateMessageDtoToJSON(json: any): CreateMessageDto {
    return CreateMessageDtoToJSONTyped(json, false);
}

export function CreateMessageDtoToJSONTyped(
    value?: CreateMessageDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        content: value["content"],
        senderId: value["senderId"],
    };
}
