/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateMessageDto } from "./CreateMessageDto";
import {
    CreateMessageDtoFromJSON,
    CreateMessageDtoFromJSONTyped,
    CreateMessageDtoToJSON,
    CreateMessageDtoToJSONTyped,
} from "./CreateMessageDto";

/**
 *
 * @export
 * @interface CreateConversationDto
 */
export interface CreateConversationDto {
    /**
     * List of messages associated with the conversation
     * @type {Array<CreateMessageDto>}
     * @memberof CreateConversationDto
     */
    messages?: Array<CreateMessageDto>;
    /**
     * Identifier of the creator of the conversation
     * @type {string}
     * @memberof CreateConversationDto
     */
    creatorId: string;
    /**
     * Identifier of the partner of the conversation
     * @type {string}
     * @memberof CreateConversationDto
     */
    partnerId: string;
}

/**
 * Check if a given object implements the CreateConversationDto interface.
 */
export function instanceOfCreateConversationDto(
    value: object
): value is CreateConversationDto {
    if (!("creatorId" in value) || value["creatorId"] === undefined)
        return false;
    if (!("partnerId" in value) || value["partnerId"] === undefined)
        return false;
    return true;
}

export function CreateConversationDtoFromJSON(
    json: any
): CreateConversationDto {
    return CreateConversationDtoFromJSONTyped(json, false);
}

export function CreateConversationDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateConversationDto {
    if (json == null) {
        return json;
    }
    return {
        messages:
            json["messages"] == null
                ? undefined
                : (json["messages"] as Array<any>).map(
                      CreateMessageDtoFromJSON
                  ),
        creatorId: json["creatorId"],
        partnerId: json["partnerId"],
    };
}

export function CreateConversationDtoToJSON(json: any): CreateConversationDto {
    return CreateConversationDtoToJSONTyped(json, false);
}

export function CreateConversationDtoToJSONTyped(
    value?: CreateConversationDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        messages:
            value["messages"] == null
                ? undefined
                : (value["messages"] as Array<any>).map(CreateMessageDtoToJSON),
        creatorId: value["creatorId"],
        partnerId: value["partnerId"],
    };
}
