/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSkillDto
 */
export interface UpdateSkillDto {
    /**
     * Name of the skill
     * @type {string}
     * @memberof UpdateSkillDto
     */
    name?: string;
    /**
     * Diminutive of the skill
     * @type {string}
     * @memberof UpdateSkillDto
     */
    diminutive?: string;
    /**
     * Unique identifier for the category
     * @type {string}
     * @memberof UpdateSkillDto
     */
    categoryId?: string;
}

/**
 * Check if a given object implements the UpdateSkillDto interface.
 */
export function instanceOfUpdateSkillDto(value: object): value is UpdateSkillDto {
    return true;
}

export function UpdateSkillDtoFromJSON(json: any): UpdateSkillDto {
    return UpdateSkillDtoFromJSONTyped(json, false);
}

export function UpdateSkillDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSkillDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'diminutive': json['diminutive'] == null ? undefined : json['diminutive'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}

export function UpdateSkillDtoToJSON(json: any): UpdateSkillDto {
    return UpdateSkillDtoToJSONTyped(json, false);
}

export function UpdateSkillDtoToJSONTyped(value?: UpdateSkillDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'diminutive': value['diminutive'],
        'categoryId': value['categoryId'],
    };
}

