/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateAvailabilityDto
 */
export interface UpdateAvailabilityDto {
    /**
     * The day of the week (0-6, where 0 is Sunday and 6 is Saturday)
     * @type {number}
     * @memberof UpdateAvailabilityDto
     */
    day?: number;
    /**
     * Start time of the availability
     * @type {Date}
     * @memberof UpdateAvailabilityDto
     */
    startTime?: Date;
    /**
     * End time of the availability
     * @type {Date}
     * @memberof UpdateAvailabilityDto
     */
    endTime?: Date;
    /**
     * Unique identifier for the user
     * @type {string}
     * @memberof UpdateAvailabilityDto
     */
    userId?: string;
}

/**
 * Check if a given object implements the UpdateAvailabilityDto interface.
 */
export function instanceOfUpdateAvailabilityDto(
    value: object
): value is UpdateAvailabilityDto {
    return true;
}

export function UpdateAvailabilityDtoFromJSON(
    json: any
): UpdateAvailabilityDto {
    return UpdateAvailabilityDtoFromJSONTyped(json, false);
}

export function UpdateAvailabilityDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateAvailabilityDto {
    if (json == null) {
        return json;
    }
    return {
        day: json["day"] == null ? undefined : json["day"],
        startTime:
            json["startTime"] == null ? undefined : new Date(json["startTime"]),
        endTime:
            json["endTime"] == null ? undefined : new Date(json["endTime"]),
        userId: json["userId"] == null ? undefined : json["userId"],
    };
}

export function UpdateAvailabilityDtoToJSON(json: any): UpdateAvailabilityDto {
    return UpdateAvailabilityDtoToJSONTyped(json, false);
}

export function UpdateAvailabilityDtoToJSONTyped(
    value?: UpdateAvailabilityDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        day: value["day"],
        startTime:
            value["startTime"] == null
                ? undefined
                : value["startTime"].toISOString(),
        endTime:
            value["endTime"] == null
                ? undefined
                : value["endTime"].toISOString(),
        userId: value["userId"],
    };
}
