/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * The name of the category
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    name?: string;
    /**
     * The color of the category in hex code
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    color?: string;
}

/**
 * Check if a given object implements the UpdateCategoryDto interface.
 */
export function instanceOfUpdateCategoryDto(
    value: object
): value is UpdateCategoryDto {
    return true;
}

export function UpdateCategoryDtoFromJSON(json: any): UpdateCategoryDto {
    return UpdateCategoryDtoFromJSONTyped(json, false);
}

export function UpdateCategoryDtoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        color: json["color"] == null ? undefined : json["color"],
    };
}

export function UpdateCategoryDtoToJSON(json: any): UpdateCategoryDto {
    return UpdateCategoryDtoToJSONTyped(json, false);
}

export function UpdateCategoryDtoToJSONTyped(
    value?: UpdateCategoryDto | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        color: value["color"],
    };
}
