/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSkillControllerCreateMultiple200Response
 */
export interface UserSkillControllerCreateMultiple200Response {
    /**
     * 
     * @type {string}
     * @memberof UserSkillControllerCreateMultiple200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the UserSkillControllerCreateMultiple200Response interface.
 */
export function instanceOfUserSkillControllerCreateMultiple200Response(value: object): value is UserSkillControllerCreateMultiple200Response {
    return true;
}

export function UserSkillControllerCreateMultiple200ResponseFromJSON(json: any): UserSkillControllerCreateMultiple200Response {
    return UserSkillControllerCreateMultiple200ResponseFromJSONTyped(json, false);
}

export function UserSkillControllerCreateMultiple200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSkillControllerCreateMultiple200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UserSkillControllerCreateMultiple200ResponseToJSON(json: any): UserSkillControllerCreateMultiple200Response {
    return UserSkillControllerCreateMultiple200ResponseToJSONTyped(json, false);
}

export function UserSkillControllerCreateMultiple200ResponseToJSONTyped(value?: UserSkillControllerCreateMultiple200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

