/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSkillControllerCreateMultiple201Response
 */
export interface UserSkillControllerCreateMultiple201Response {
    /**
     * Number of skills added
     * @type {number}
     * @memberof UserSkillControllerCreateMultiple201Response
     */
    count?: number;
}

/**
 * Check if a given object implements the UserSkillControllerCreateMultiple201Response interface.
 */
export function instanceOfUserSkillControllerCreateMultiple201Response(value: object): value is UserSkillControllerCreateMultiple201Response {
    return true;
}

export function UserSkillControllerCreateMultiple201ResponseFromJSON(json: any): UserSkillControllerCreateMultiple201Response {
    return UserSkillControllerCreateMultiple201ResponseFromJSONTyped(json, false);
}

export function UserSkillControllerCreateMultiple201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSkillControllerCreateMultiple201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function UserSkillControllerCreateMultiple201ResponseToJSON(json: any): UserSkillControllerCreateMultiple201Response {
    return UserSkillControllerCreateMultiple201ResponseToJSONTyped(json, false);
}

export function UserSkillControllerCreateMultiple201ResponseToJSONTyped(value?: UserSkillControllerCreateMultiple201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

