/* tslint:disable */
/* eslint-disable */
/**
 * SkillSwap API
 * API for the SkillSwap skills exchange platform
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvailabilityResponseDto } from './AvailabilityResponseDto';
import {
    AvailabilityResponseDtoFromJSON,
    AvailabilityResponseDtoFromJSONTyped,
    AvailabilityResponseDtoToJSON,
    AvailabilityResponseDtoToJSONTyped,
} from './AvailabilityResponseDto';

/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * Unique identifier for the user
     * @type {string}
     * @memberof UserResponseDto
     */
    id: string;
    /**
     * User email address
     * @type {string}
     * @memberof UserResponseDto
     */
    email: string;
    /**
     * User password (minimum 8 characters, 1 uppercase, 1 lowercase, 1 number and 1 special character)
     * @type {string}
     * @memberof UserResponseDto
     */
    password?: string;
    /**
     * User first name
     * @type {string}
     * @memberof UserResponseDto
     */
    firstName: string;
    /**
     * User last name
     * @type {string}
     * @memberof UserResponseDto
     */
    lastName: string;
    /**
     * User biography
     * @type {string}
     * @memberof UserResponseDto
     */
    biography?: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof UserResponseDto
     */
    avatarUrl?: string;
    /**
     * Indicates if the user account is archived
     * @type {boolean}
     * @memberof UserResponseDto
     */
    isArchived: boolean;
    /**
     * Date when the user was created
     * @type {Date}
     * @memberof UserResponseDto
     */
    createdAt: Date;
    /**
     * Date when the user was last updated
     * @type {Date}
     * @memberof UserResponseDto
     */
    updatedAt: Date;
    /**
     * List of user availabilities
     * @type {Array<AvailabilityResponseDto>}
     * @memberof UserResponseDto
     */
    availabilities: Array<AvailabilityResponseDto>;
}

/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): value is UserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('isArchived' in value) || value['isArchived'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('availabilities' in value) || value['availabilities'] === undefined) return false;
    return true;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'isArchived': json['isArchived'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'availabilities': ((json['availabilities'] as Array<any>).map(AvailabilityResponseDtoFromJSON)),
    };
}

export function UserResponseDtoToJSON(json: any): UserResponseDto {
    return UserResponseDtoToJSONTyped(json, false);
}

export function UserResponseDtoToJSONTyped(value?: UserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'biography': value['biography'],
        'avatarUrl': value['avatarUrl'],
        'isArchived': value['isArchived'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'availabilities': ((value['availabilities'] as Array<any>).map(AvailabilityResponseDtoToJSON)),
    };
}

