name: Build and Push Docker Images to GHCR 🐳

# This workflow is triggered manually or after a successful merge
on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger after successful merge from develop to main
  repository_dispatch:
    types: [ build-api-trigger ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push frontend image (Next.js prod target from Dockerfile)
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skillswap-frontend:latest -f frontend/Dockerfile --target prod frontend
          docker push ghcr.io/${{ github.repository_owner }}/skillswap-frontend:latest

      # Build and push backend image (NestJS prod target from Dockerfile)
      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skillswap-api:latest -f skillswap-api/Dockerfile --target prod skillswap-api
          docker push ghcr.io/${{ github.repository_owner }}/skillswap-api:latest
  
  # Job qui appelle le workflow de déploiement.
  call-deploy-workflow:
    needs: build
    uses: ./.github/workflows/deploy-skillswap-api.yml
    secrets: inherit

