name: Build and Push Docker Images to GHCR 🐳

# This workflow is triggered manually or after a successful merge
on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger after successful merge from develop to main
  repository_dispatch:
    types: [ build-api-trigger ]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push frontend image (Next.js dev image as defined by Dockerfile)
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skillswap-frontend:latest -f frontend/Dockerfile frontend
          docker push ghcr.io/${{ github.repository_owner }}/skillswap-frontend:latest

      # Build and push backend image (NestJS prod target from Dockerfile)
      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skillswap-api:latest -f skillswap-api/Dockerfile --target prod skillswap-api
          docker push ghcr.io/${{ github.repository_owner }}/skillswap-api:latest
  
  # Separate job that triggers the deployment workflow after a successful build
  trigger-deploy-workflow:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy API Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-api-trigger
